project:
  type: website

website:
  title: "Visualizing Laboratory Data"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: best_practices.qmd
        text: "Best Practices"
      - about.qmd

format:
  html:
    toc: true
    toc-depth: 2
    warning: false
    code-fold: true
    code-summary: "Show the Code"
    embed-resources: true
    grid:
      sidebar-width: 300px
      body-width: 1300px
      margin-width: 300px
      gutter-width: 1.5rem
    css: styles.css
    
execute:
  cache: true

editor: visual

